package io.taucoin.core;

public enum DataType {
    MUTABLE_ITEM_BLOCK_HASH,
    MUTABLE_ITEM_TX_HASH,
    BLOCK,
    TX,
    MUTABLE_ITEM_BLOCK_HASH_FOR_VOTING,
    MUTABLE_ITEM_BLOCK_FOR_VOTING,
    TX_FOR_POOL,
}
